sudo: required
dist: trusty

language: ruby
cache: bundler

rvm:
  - 2.3.0

before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install coinor-cbc -y
  - gem install bundler

before_script:
  - psql -c 'create database "gta-assignment_test";' -U postgres

script:
  - bundle exec rake db:schema:load
  - bundle exec rake spec

after_failure:
  - echo $RAILS_ENV
  - bundle exec rake --version
  - cbc version 
