sudo: false
language: ruby
cache: bundler

rvm:
  - 2.3.0

before_script:
  - psql -c 'create database "gta-assignment_test";' -U postgres

script:
  - rake db:schema:load
  - rake spec

after_failure:
  - echo $RAILS_ENV
  - rake --version
